### ISSUE TITLE
librevault-daemon 0.1.18 immediately crashes

### ISSUE THREAD

**Issue by interfect** [Librevault/librevault#53]
On Ubuntu 16.04, librevault-daemon crashes immediately on startup like this:

```
(gdb) run
Starting program: /usr/bin/librevault-daemon 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
   __    __ _                                _ __ 
  / /   /_/ /_  ____ _____ _  __ ___  __  __/ / /_
 / /   __/ /_ \/ ___/ ___/ / / / __ \/ / / / / __/
/ /___/ / /_/ / /  / ___/\ \/ / /_/ / /_/ / / /___
\____/_/\____/_/  /____/  \__/_/ /_/\____/_/\____/
[2016-08-19 18:39:18.686431] [T:8311] [I] Librevault 0.1.18
terminate called after throwing an instance of 'websocketpp::exception'
  what():  Underlying Transport Error

Program received signal SIGABRT, Aborted.
0x00007ffff5017418 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff5017418 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff501901a in __GI_abort () at abort.c:89
#2  0x00007ffff595984d in __gnu_cxx::__verbose_terminate_handler() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff59576b6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff5957701 in std::terminate() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff5957919 in __cxa_throw ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00000000005fc106 in librevault::WSServer::WSServer(librevault::Client&, librevault::P2PProvider&) ()
#7  0x00000000005f7b40 in librevault::P2PProvider::P2PProvider(librevault::Client&) ()
#8  0x00000000006a4438 in librevault::Client::Client(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, docopt::value, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, docopt::value> > >) ()
#9  0x000000000056b91d in main ()
(gdb) 
```

I've run it under gdb to get a backtrace; apparently a websocket error isn't being handled when it can't talk to something.

During normal use, this manifests as not being able to save any settings changes made in the GUI, and as those Ubuntu "system problem detected" dialogs popping up.

I've been seeing similar behavior on Windows, where 0.1.18 would have librevault-daemon crash immediately on startup. 0.1.17 would work fine; I'm about to try that on Ubuntu.

This issue might be related to my weird home network setup and my proliferation of IPv6-only virtual TUN interfaces on my machines.

**Comment by interfect** [comment]
This doesn't happen all the time; eventually (?) the GUI seems to get the daemon to start up properly and things work.

**Comment by GamePad64** [comment]
The first assumption on this error is that the port (42345 by default) is already bound to some other application. The second assumption is the lack of IPv6 stack on your computer. Please, describe your network setup. Maybe, there is something, that could prevent daemon from binding to "[::]:42345"?

**Comment by GamePad64** [comment]
This behavior may be observed on restarting the GUI.
librevault-daemon may have an unexpected pause before actually stopping its execution. So, the restarted GUI tries to run a new process, but the old one did not release the port. And the new daemon throws an exception.

**Comment by interfect** [comment]
I don't see any other users of port 42345 on my system.

I also definitely do have an IPv6 stack.

I just looked on my system and it seems the GUI was up but the daemon wasn't running. It looks like this bug may be related to the state of my system on startup? Or maybe SO_REUSEADDR not being used when it should be?

**Comment by interfect** [comment]
In my system's current state I can start the daemon and it gets far enough into indexing to run into #61.
